
# Advance-Machine-Learning-TDDE15

```{r setup, include=FALSE, echo=FALSE, results='hide',message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

```



## Lab 1 - Graphical Models

More Information is in the Lab 1 folder. 

The first lab is about **Graphical Models** and brings up concepts such as

- Equality between graphs by determining if they have the same adjacencies and unshielded colliders
- Markov blankets and independences
- Naïve Bayes classifiers 

And an overall discussion about what influences predictions in Bayesian Networks and Markov Models.

## Lab 2 - Hidden Markov Models

More information is in the Lab 2 folder.

Main purpose of lab was to gain deeper insight into: 

- Hidden Markov Models (Transition matrix, emission matrix)
- The forward-backward algorithm
- Two different distributions obtained by alpha and beta, the Smoothed Distribution and the Filtered Distribution
- Entropy and knowledge of the position of a robot
- Future predictions of states 

